version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/go_app?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=go_app
  redis:
    image: redis:alpine
    container_name: fiber-redis
    # hostname: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
  web:
    container_name: web
    command: bash -c "npm run build"
    volumes:
      - ./web:/www
    ports:
      - 8080:8080
